# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dog_breed_id',
                'doc_host': 'https://dhrits.github.io',
                'git_url': 'https://github.com/dhrits/dog_breed_id',
                'lib_path': 'dog_breed_id'},
  'syms': { 'dog_breed_id.core': {'dog_breed_id.core.foo': ('core.html#foo', 'dog_breed_id/core.py')},
            'dog_breed_id.data_download': { 'dog_breed_id.data_download.download_file': ( 'data_download.html#download_file',
                                                                                          'dog_breed_id/data_download.py')}}}
